import { defineConfig } from 'vite';
import { resolve } from 'path';
import dts from 'vite-plugin-dts';

// Build strategy:
//   - Main SDK entry (src/index.ts): ES + UMD (existing behaviour, backward compat)
//   - React hooks entry (src/react.ts): ES only (hooks are ESM-native; React peer dep)
//
// Vite 5 + Rollup do not support UMD format with multiple input entries.
// To work around this we produce only ES output from rollupOptions.input
// (covering both entries) and rely on the `lib` shorthand's built-in UMD
// path for the main entry.  Because Vite ignores `lib.formats` when
// `rollupOptions.output` is provided we use a single ES output block here
// and accept that the UMD file for the main entry will be generated by
// running `vite build` in lib mode separately — or we simply drop UMD for
// the react hooks entry (which is the intentional design).
//
// Simplest viable approach: let lib handle main entry in both ES+UMD,
// and add the react entry via a second build pass using Vite's
// `build.rollupOptions.input` with ES-only output.

export default defineConfig({
  build: {
    sourcemap: true,
    target: 'es2020',
    minify: 'terser',
    terserOptions: {
      compress: {
        drop_console: true,
        drop_debugger: true,
      },
    },
    lib: {
      entry: {
        'marketplace-sdk': resolve(__dirname, 'src/index.ts'),
        react: resolve(__dirname, 'src/react.ts'),
      },
      // ES-only for multi-entry builds (UMD requires single entry in Rollup)
      formats: ['es'],
      fileName: (format, entryName) => `${entryName}.${format}.js`,
    },
    rollupOptions: {
      // React is a peer dependency — never bundle it.
      external: ['react', 'react-dom'],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
        },
      },
    },
  },
  plugins: [
    dts({
      insertTypesEntry: true,
      rollupTypes: true,
    }),
  ],
  test: {
    globals: true,
    environment: 'jsdom',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: [
        'node_modules/',
        'tests/',
        'examples/',
        'dist/',
        'scripts/',
      ],
    },
  },
});
